### PR TITLE
[quality] add unit tests for tool_registry.go infrastructure

### LINKED ISSUE #257: [quality] Missing unit tests for tool_registry.go and registry init files
## Finding

The tool registry pattern introduced in PR #256 has no dedicated unit test coverage. The following files have zero tests:

- `pkg/mcp/server/tool_registry.go` — Core registry infrastructure (`RegisterTool`, `registeredTools`, `findToolHandler`)
- `pkg/mcp/server/tools_cluster_registry.go`
- `pkg/mcp/server/tools_drift_registry.go`
- `pkg/mcp/server/tools_policy_registry.go`
- `pkg/mcp/server/tools_rbac_registry.go`
- `pkg/mcp/server/tools_workloads_registry.go`
- `pkg/mcp/server/upgrades_registry.go`

While `server_test.go::TestHandleToolsListIncludesDiagnosticsAndUpgradeTools` exercises the registry indirectly, there are no tests verifying:
1. `RegisterTool` appends correctly and handles duplicate names
2. `findToolHandler` returns nil for unknown tools
3. Each registry init file actually registers the expected tools (schema/handler consistency)
4. Registry integrity after all init() calls complete (no nil handlers, no empty schemas)

## Recommendation

1. Add `pkg/mcp/server/tool_registry_test.go` covering the core registry functions
2. Add a registry integrity test that iterates all registered tools and asserts schema completeness (non-empty Name, Description, InputSchema) and non-nil handler
3. This protects against regressions when new tools are added via the registry pattern

## Priority
- Impact: high (registry is single dispatch point for all 38+ tools)
- Effort: low (straightforward unit tests)

---
*Filed by quality agent (ACMM L4/L6 — full mode)*

### PR DESCRIPTION
**Pull request by clubanderson**
## Test Improvement

Adds dedicated unit tests for the tool registry infrastructure (`tool_registry.go`) introduced in PR #256. The registry is the single dispatch point for all 38+ MCP tools, yet had zero dedicated test coverage.

### Tests added

| Test | Purpose |
|------|---------|
| `TestFindToolHandler_ReturnsNilForUnknownTool` | Verifies nil return for missing tools |
| `TestFindToolHandler_ReturnsHandlerForKnownTool` | Verifies lookup of `list_clusters` |
| `TestRegisteredTools_ReturnsNonEmptyList` | Init files actually populate the registry |
| `TestRegisteredTools_AllHaveNonEmptyName` | No empty schema names |
| `TestRegisteredTools_AllHaveDescription` | All tools are documented |
| `TestRegisteredTools_AllHaveHandler` | No nil handlers registered |
| `TestRegisteredTools_NoDuplicateNames` | Catches accidental double-registration |
| `TestRegisteredTools_CountMatchesRegistry` | `registeredTools()` slice consistency |
| `TestRegisteredTools_InputSchemaHasObjectType` | Schema structure validation |

These tests act as a safety net: any new tool added via the registry pattern will automatically be validated for completeness without needing per-tool test additions.

Fixes #257

---
*Filed by quality agent (ACMM L4/L6 — full mode)*

### CODE REVIEW

**Comment by clubanderson** [comment]
⚠️ **CI Blocker Note**: The `build` and `lint` failures on this PR are **not caused by this PR's changes**. They are pre-existing compilation errors on `main`:

1. Duplicate `TestToolGetUpgradeStatus_ClientError` in `upgrades_test.go` + `upgrades_coverage_test.go`
2. Unused `"context"` import in `upgrades_test.go`
3. Invalid type assertion on `DeleteResult` struct in `pkg/deploy/mcp/tools_kubectl_handlers_test.go`

Fix PR: #260 (once merged, this PR's CI should pass)
